class State:
    START_POINT = 1
    GET_LANGUAGE = 2
    GET_USER_TYPE = 3

    #exibitor

    GET_FULL_NAME_EXIBITOR = 4
    GET_COUNTRY_NAME_EXIBITOR = 5
    GET_PHONE_NUMBER_NAME_EXIBITOR = 6
    GET_EMAIL_EXIBITOR = 7
    GET_COMPANY_NAME_EXIBITOR=17

    #visitor



    GET_NAME_VISITOR = 9
    GET_SURNAME_VISITOR = 10
    GET_COUNTRY_VISITOR = 11
    GET_REGION_VISITOR = 12
    PERSONALITY_TYPE_VISITOR = 13
    GET_PHONE_NUMBER_VISITOR = 14
    GET_EMAIL_VISITOR = 15







state = State()
