# Generated by Django 4.2.1 on 2023-05-19 06:17

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityOfYourCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='First name')),
            ],
            options={
                'verbose_name': 'Activity Of Your Company',
                'verbose_name_plural': 'Activity Of Your Companies',
            },
        ),
        migrations.CreateModel(
            name='ChoiceOfService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='First name')),
            ],
            options={
                'verbose_name': 'Choice Of Service',
                'verbose_name_plural': 'Choice Of Services',
            },
        ),
        migrations.CreateModel(
            name='HearingUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
            ],
            options={
                'verbose_name': 'Hearing Us',
                'verbose_name_plural': 'Hearing Us',
            },
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=100, verbose_name='First name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last name')),
                ('personality', models.CharField(choices=[('Physical', 'Physical'), ('Legal', 'Legal')], default='Physical', max_length=10, verbose_name='Personality')),
                ('company_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Company name')),
                ('job_title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Job title')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Website')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Phone')),
                ('email', models.EmailField(max_length=255, verbose_name='Email')),
                ('feedback', models.TextField(blank=True, null=True, verbose_name='Feedback')),
                ('activity', models.ManyToManyField(to='application.activityofyourcompany', verbose_name='Activities')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.country', verbose_name='Country')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.region', verbose_name='Region')),
                ('service', models.ManyToManyField(to='application.choiceofservice', verbose_name='Services')),
            ],
            options={
                'verbose_name': 'Visitor',
                'verbose_name_plural': 'Visitors',
            },
        ),
        migrations.CreateModel(
            name='BookStand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('company_name', models.CharField(max_length=255, verbose_name='Company name')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Phone')),
                ('email', models.EmailField(max_length=255, verbose_name='Email')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.country', verbose_name='Country')),
                ('hear_us', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.hearingus', verbose_name='Hearing us')),
            ],
            options={
                'verbose_name': 'Book Stand',
                'verbose_name_plural': 'Book Stands',
            },
        ),
    ]
