# Generated by Django 4.2.1 on 2023-05-20 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('name_en', models.CharField(max_length=200, null=True)),
                ('name_ru', models.CharField(max_length=200, null=True)),
                ('name_uz', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TelegramProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.PositiveBigIntegerField(unique=True)),
                ('telegram_id_en', models.PositiveBigIntegerField(null=True, unique=True)),
                ('telegram_id_ru', models.PositiveBigIntegerField(null=True, unique=True)),
                ('telegram_id_uz', models.PositiveBigIntegerField(null=True, unique=True)),
                ('first_name', models.CharField(max_length=255, null=True)),
                ('first_name_en', models.CharField(max_length=255, null=True)),
                ('first_name_ru', models.CharField(max_length=255, null=True)),
                ('first_name_uz', models.CharField(max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name_en', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name_ru', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name_uz', models.CharField(blank=True, max_length=255, null=True)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('username_en', models.CharField(blank=True, max_length=255, null=True)),
                ('username_ru', models.CharField(blank=True, max_length=255, null=True)),
                ('username_uz', models.CharField(blank=True, max_length=255, null=True)),
                ('language', models.CharField(choices=[('uz', 'Uzbek'), ('ru', 'Russian'), ('en', 'English')], default='en', max_length=255, null=True)),
                ('language_en', models.CharField(choices=[('uz', 'Uzbek'), ('ru', 'Russian'), ('en', 'English')], default='en', max_length=255, null=True)),
                ('language_ru', models.CharField(choices=[('uz', 'Uzbek'), ('ru', 'Russian'), ('en', 'English')], default='en', max_length=255, null=True)),
                ('language_uz', models.CharField(choices=[('uz', 'Uzbek'), ('ru', 'Russian'), ('en', 'English')], default='en', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('name_en', models.CharField(max_length=200, null=True)),
                ('name_ru', models.CharField(max_length=200, null=True)),
                ('name_uz', models.CharField(max_length=200, null=True)),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.country')),
                ('country_en', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.country')),
                ('country_ru', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.country')),
                ('country_uz', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.country')),
            ],
        ),
    ]
