# Generated by Django 4.2.1 on 2023-05-20 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_alter_telegramprofile_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='country',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='country',
            name='name_uz',
        ),
        migrations.RemoveField(
            model_name='region',
            name='country_en',
        ),
        migrations.RemoveField(
            model_name='region',
            name='country_ru',
        ),
        migrations.RemoveField(
            model_name='region',
            name='country_uz',
        ),
        migrations.RemoveField(
            model_name='region',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='region',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='region',
            name='name_uz',
        ),
        migrations.RemoveField(
            model_name='telegramprofile',
            name='first_name_en',
        ),
        migrations.RemoveField(
            model_name='telegramprofile',
            name='first_name_ru',
        ),
        migrations.RemoveField(
            model_name='telegramprofile',
            name='first_name_uz',
        ),
        migrations.RemoveField(
            model_name='telegramprofile',
            name='language_en',
        ),
        migrations.RemoveField(
            model_name='telegramprofile',
            name='language_ru',
        ),
        migrations.RemoveField(
            model_name='telegramprofile',
            name='language_uz',
        ),
        migrations.RemoveField(
            model_name='telegramprofile',
            name='last_name_en',
        ),
        migrations.RemoveField(
            model_name='telegramprofile',
            name='last_name_ru',
        ),
        migrations.RemoveField(
            model_name='telegramprofile',
            name='last_name_uz',
        ),
        migrations.RemoveField(
            model_name='telegramprofile',
            name='telegram_id_en',
        ),
        migrations.RemoveField(
            model_name='telegramprofile',
            name='telegram_id_ru',
        ),
        migrations.RemoveField(
            model_name='telegramprofile',
            name='telegram_id_uz',
        ),
        migrations.RemoveField(
            model_name='telegramprofile',
            name='username_en',
        ),
        migrations.RemoveField(
            model_name='telegramprofile',
            name='username_ru',
        ),
        migrations.RemoveField(
            model_name='telegramprofile',
            name='username_uz',
        ),
        migrations.AlterField(
            model_name='telegramprofile',
            name='language',
            field=models.CharField(blank=True, choices=[('uz', 'Uzbek'), ('ru', 'Russian'), ('en', 'English')], default='uz', max_length=255, null=True),
        ),
    ]
