# Generated by Django 4.2.1 on 2023-05-22 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_remove_country_name_en_remove_country_name_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='region',
            name='country',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='Region',
        ),
    ]
